triggerID:
  in: path
  name: triggerID
  required: true
  schema:
    type: string
    format: uuid
  description: The ID of updated trigger
  example: 5A8AF369-86D2-44DD-B514-D47995ED6AF7

targetID:
  in: query
  name: targetID
  required: false
  schema:
    type: string
  description: The ID of updated target to print plot for
  example: t1

from:
  in: query
  name: from
  required: false
  schema:
    type: string
  description: The start period of metrics to get
  example: -1hour

to:
  in: query
  name: to
  required: false
  schema:
    type: string
  description: The end period of metrics to get
  example: now
