name: Delete spec version from SwaggerHub

on:
  [delete]

jobs:
  removespec:
    name: Remove the corresponding spec from SwaggerHub
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set output for versioning
        id: vars
        run: echo ::set-output name=tag::"${GITHUB_REF#refs/*/}"

      - name: remove spec from swaggerhub
        env:
          AUTH_TOKEN: ${{secrets.SWAGGERHUB_TOKEN}}
          BRANCH_NAME: ${{ github.event.ref }}
          SWAGGERHUB_URL: "https://api.swaggerhub.com/apis/moira/moira-alert"
        shell: bash
        run: |
          VERSION=`echo ${BRANCH_NAME}|sed 's#[^a-zA-Z0-9_\.\-]#_#g'`
          curl -X DELETE "${SWAGGERHUB_URL}/${VERSION}" -H "content-type: application/yaml" -H "Authorization: ${AUTH_TOKEN}"
